import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.scss';
import ModalProvider from '@/providers/ModalProvider';

const openSans = Open_Sans({
    subsets: ['latin', 'cyrillic'],
    weight: ['300', '400', '500', '600', '700', '800'],
    variable: '--font-open-sans',
    display: 'swap',
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={openSans.variable}>
            <body>
                <ModalProvider>{children}</ModalProvider>
            </body>
        </html>
    );
}
