services:
  frontend:
    container_name: pizzaro-frontend
    restart: unless-stopped 
    build:
      context: ./frontend
      dockerfile: .Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: pizzaro-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  db_data: